# Generated by Django 4.0.3 on 2022-06-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
