# Generated by Django 4.0.3 on 2022-06-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0005_remove_card_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/photos'),
        ),
    ]
